name: msix
description: A command-line tool that create Msix installer from your flutter windows-build files.
version: 3.16.8
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix
issue_tracker: https://github.com/YehudaKremer/msix/issues
topics:
  - windows
  - tool
screenshots:
  - description: "A command-line tool that create Msix installer from your flutter windows-build files."
    path: doc/screenshot.png

platforms:
  windows:

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.3.0
  yaml: ^3.1.0
  path: ^1.8.0
  package_config: ^2.1.0
  get_it: ^8.0.3
  image: ^4.0.9
  pub_semver: ^2.1.0
  console: ^4.1.0
  cli_util: ^0.4.0

dev_dependencies:
  test: ^1.23.0
  flutter_lints: ^5.0.0
