name: msix
description: Create and sign Msix installer for flutter windows-build files.
version: 0.2.0-nullsafety.0
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: Msix
        pluginClass: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  yaml: ^3.0.0-nullsafety.0
  ansicolor: ^2.0.0-nullsafety.0
  args: ^2.0.0-nullsafety.0