name: msix
description: A command-line tool that create Msix installer from your flutter windows-build files.
version: 3.8.3
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix
issue_tracker: https://github.com/YehudaKremer/msix/issues
screenshots:
  - description: "A command-line tool that create Msix installer from your flutter windows-build files."
    path: doc/screenshot.png

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: Msix
        pluginClass: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.0
  yaml: ^3.1.0
  path: ^1.8.0
  package_config: ^2.1.0
  get_it: ^7.2.0
  image: ^4.0.0
  pub_semver: ^2.1.0
  console: ^4.1.0
  cli_util: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.23.0
